CREATE TABLE users (
    'LOGIN' VARCHAR PRIMARY KEY,
    'PASSWORD' VARCHAR NOT NULL,
    'RANK' VARCHAR NOT NULL DEFAULT 'NORMAL',
    CHECK (RANK IN ('NORMAL','VIP','ADMIN'))
);

CREATE TABLE canvas (
    id VARCHAR PRIMARY KEY,
    owner VARCHAR NOT NULL,
    height INTEGER NOT NULL,
    length INTEGER NOT NULL,
    FOREIGN KEY(owner) REFERENCES users(login)
);